name: Copy updated build folder

# only run this workflow when the build folder has changed on the main branch
on: 
  push:
    branches: 
      - main
    paths:
      - 'dmlung_test/build'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  copy_build_to_site_repo: 
    runs-on: ubuntu-latest
    steps:
    # check out dmlung_test project
    - name: Check out dmlung_test project
      uses: actions/checkout@v3
    # check out dmlung-test-io project using token generated in that project to successfully access it from inside the dmlung_test GitHub Action workflow
    - name: Check out dmlung-test-io project
      uses: actions/checkout@v3
      with:
        repository: dmlung/dmlung-test-io
        path: ./dmlung-test-io
        token: ${{ secrets.DMLUNG_TEST_IO_TOKEN }}
    # make a copy of the build folder file from dmlung_test project
    - name: Copy build folder
      run: bash ./.github/scripts/copy-build-folder.sh
      env:
        DESTINATION_REPO: ./dmlung-test-io/
        DESTINATION_TAG: v1.0-post
    # push the copy of the dmlung_test build folder there
    - name: Push to dmlung-test-io repo
      run: bash ./.github/scripts/push-build-to-dmlung-test-io.sh
      env:
        DESTINATION_REPO: ./dmlung-test-io